file added

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -8,10 +8,17 @@ if [ "$#" -lt 4 ]; then
 fi
 
 # Assigning the passed arguments to variables
-PATH_TO_FILE=$1
-IP=$2
-USERNAME=$3
-PATH_TO_SSH_KEY=$4
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
 # Transferring the file to the server
 scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
+
+# Checking if transfer was successful
+if [ "$?" -eq 0 ]; then
+    echo "File transferred successfully"
+else
+    echo "Error: File transfer failed"
+fi
